<?php

/**
 * Implements hook_help().
 */

function table_module_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match)
{
    switch ($route_name) {
            // Main module help for the block module.
        case 'help.page.table_module':
            return '<p> Este es el hook help del módulo generado para la visualización y edición de una tabla basada en la información de usuarios.</p>';
    }
}


function table_module_theme($existing, $type, $theme, $path)
{
    return [
        'table_module_welcome_template' => [
            'variables' => [
                'title' => NULL,
                'welcome_text' => NULL,
            ]
        ]
    ];
}
